name: Release

on: 
  push:
    tags:
      - "*"

jobs:
  release-to-gitHub:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          # same with pubspec.yaml
          flutter-version: "1.20.2"
      - run: flutter pub get
        working-directory: dart_native/example
      - run: flutter analyze --no-pub --no-current-package lib/ test/
        working-directory: dart_native/example
      - run: flutter test --no-pub test/
        working-directory: dart_native/example
      - run: flutter build apk
        working-directory: dart_native/example
      - uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
